## Rigid 변환 구하기


In [20]:
# R1R2를 하나의 translation matrix로 생각하면 3x3의 행렬을 구하는 식으로 생각할 수 있다.
# 세 쌍의 점이므로 등식 또한 9개가 만들어진다.
# 세개의 방정식의 해를 구하는 방법으로 각 행의 요소를 구하면 된다.
from sympy import Symbol, solve 
a = Symbol('a')
b = Symbol('b')
c = Symbol('c')
equation1 = p1[0]*a+p1[1]*b+p1[2]*c-p1_[0]
equation2 = p2[0]*a+p2[1]*b+p2[2]*c-p2_[0]
equation3 = p3[0]*a+p3[1]*b+p3[2]*c-p3_[0]
solve(equation1,equation2, equation3,dict=True)

[]

In [21]:

equation1 = a + 2 * b+c - 3
equation2 = 3 * a - b-c + 2
solve((equation1, equation2), dict=True)


[{b: -4*c/7 + 11/7, a: c/7 - 1/7}]

In [1]:
import numpy as np
import math
p1o = np.array([-.5, 0, 2.12])    # _o : original(A 점들)
p2o = np.array([.5, 0, 2.12])
p3o = np.array([.5, -.71,2.83])
p4o = np.array([.5, .71, 2.83])
p5o = np.array([1, 1, 1])
p1o_ = np.array([1.36,-.43,2.34]) # p' (A' 점들)
p2o_ = np.array([1.75, .44, 2.02])
p3o_ = np.array([2.64, .18, 2.40])
p4o_ = np.array([1.50, .87, 2.88])

# p1이 원점이 되도록 A를 평행이동 = vector
p1 = p1o - p1o
p2 = p2o - p1o
p3 = p3o - p1o
p4 = p4o - p1o
p5 = p5o - p1o
p1_ = p1o_ - p1o_
p2_ = p2o_ - p1o_
p3_ = p3o_ - p1o_
p4_ = p4o_ - p1o_

In [14]:
# magnitude 구하는 함수
def mag(x): 
    return math.sqrt(sum(i**2 for i in x))

def mat_mul(r,x):
    a = np.array([x[0]*r[0] , x[1]*r[1] , x[2]*r[2]])
    return a
def mat_vec(R,x):
    a = np.array([np.sum(mat_mul(R[0],x)),np.sum(mat_mul(R[1],x)),np.sum(mat_mul(R[2],x))])
    return a

In [3]:
# original 점 3개로 평면 정의 (법선 벡터 구하기)
# translation의 점 3개로 평면 정의 (법선 벡터 구하기)
h = np.array([p2[1]*p3[2]-p3[1]*p2[2], -p2[0]*p3[2]+p3[0]*p2[2],  p2[0]*p3[1]- p3[0]*p2[1] ]) #h
h_ = np.array([p2_[1]*p3_[2]-p3_[1]*p2_[2], -p2_[0]*p3_[2]+p3_[0]*p2_[2],  p2_[0]*p3_[1]- p3_[0]*p2_[1] ]) #h_

# 두 평면의 법선벡터의 cross product 결과
n_ot_raw = np.array([h[1]*h_[2]-h_[1]*h[2], -h[0]*h_[2]+h_[0]*h[2],  h[0]*h_[1]- h_[0]*h[1]])
sin = mag(n_ot_raw)/(mag(h)*mag(h_))
n_ot = n_ot_raw/mag(n_ot_raw)

# dot product로 cos 구하기
dot_ot = np.sum(h*h_)
cos = dot_ot/(mag(h)*mag(h_))

# 공식 그대로 해서 R1 구하기
r1 = cos+n_ot[0]*n_ot[0]*(1-cos)
r2 = n_ot[0]*n_ot[1]*(1-cos)-n_ot[2]*sin
r3 = n_ot[0]*n_ot[2]*(1-cos)+n_ot[1]*sin
r4 = n_ot[1]*n_ot[0]*(1-cos)+n_ot[2]*sin
r5 = cos+n_ot[1]*n_ot[1]*(1-cos)
r6 = n_ot[1]*n_ot[2]*(1-cos)-n_ot[0]*sin
r7 = n_ot[0]*n_ot[2]*(1-cos)-n_ot[1]*sin
r8 = n_ot[2]*n_ot[1]*(1-cos)+n_ot[0]*sin
r9 = cos+n_ot[2]*n_ot[2]*(1-cos)
R1 = np.array([[r1,r2,r3],[r4,r5,r6],[r7,r8,r9]])

xco = np.sum(mat_mul(R1[0],h))
yco = np.sum(mat_mul(R1[1],h))
zco = np.sum(mat_mul(R1[2],h))
print(xco,yco,zco)
print(h_)

0.24650355585587463 -0.4314310415747523 -0.8725269355820108
[ 0.2474 -0.433  -0.8757]


In [10]:
R1

array([[ 0.96858134, -0.20170448, -0.14548363],
       [ 0.14548363,  0.93398959, -0.32634024],
       [ 0.20170448,  0.29492158,  0.93398959]])

In [11]:
R2

array([[ 0.46823522, -0.84250333,  0.26635301],
       [ 0.72312259,  0.53860058,  0.43243859],
       [-0.50778884, -0.0098771 ,  0.86142495]])

In [9]:
# 공식 그대로 R2 구하기
# h_ 가 회전축, p3, p3_로 각도 구하기
# p3의 cross product

# R1(p3-p1) -> p3_-p1_
p3d = np.array([np.sum(mat_mul(R1[0],p3)),np.sum(mat_mul(R1[1],p3)),np.sum(mat_mul(R1[2],p3))])

p3_c = np.array([p3d[1]*p3_[2]-p3_[1]*p3d[2], -p3d[0]*p3_[2]+p3_[0]*p3d[2],  p3d[0]*p3_[1]- p3_[0]*p3d[1]])
sin3 = mag(p3_c)/(mag(p3d)*mag(p3_))
n_ot3 = p3_c/mag(p3_c)
# p3의 dot product
p3_d = np.sum(p3d*p3_)
cos3 = p3_d/(mag(p3d)*mag(p3_))

# 공식 그대로 해서 R2구하기
r1_ = cos3+n_ot3[0]*n_ot3[0]*(1-cos3)
r2_ = n_ot3[0]*n_ot3[1]*(1-cos3)-n_ot3[2]*sin3
r3_ = n_ot3[0]*n_ot3[2]*(1-cos3)+n_ot3[1]*sin3
r4_ = n_ot3[1]*n_ot3[0]*(1-cos3)+n_ot3[2]*sin3
r5_ = cos3+n_ot3[1]*n_ot3[1]*(1-cos3)
r6_ = n_ot3[1]*n_ot3[2]*(1-cos3)-n_ot3[0]*sin3
r7_ = n_ot3[0]*n_ot3[2]*(1-cos3)-n_ot3[1]*sin3
r8_ = n_ot3[2]*n_ot3[1]*(1-cos3)+n_ot3[0]*sin3
r9_ = cos3+n_ot3[2]*n_ot3[2]*(1-cos3)
R2 = np.array([[r1_,r2_,r3_],[r4_,r5_,r6_],[r7_,r8_,r9_]])

xco = np.sum(mat_mul(R2[0],p3d))
yco = np.sum(mat_mul(R2[1],p3d))
zco = np.sum(mat_mul(R2[2],p3d))
print(xco,yco,zco)
print(p3_)

1.278123842231119 0.6091058935632676 0.05991205510458375
[1.28 0.61 0.06]


In [8]:
# p2 확인
xco = np.sum(mat_mul(R2[0],p2))
yco = np.sum(mat_mul(R2[1],p2))
zco = np.sum(mat_mul(R2[2],p2))
print(xco,yco,zco)
print(p2_)

0.4682352161247249 0.7231225869623845 -0.5077888405680661
[ 0.39  0.87 -0.32]


In [19]:
print(p4_)
print(mat_vec(R2,(mat_vec(R1,p4))))

[0.14 1.3  0.54]
[0.1381745  1.29741646 0.55300845]


In [21]:
print(mat_vec(R2,(mat_vec(R1,p5))))

[-0.73602845  1.64602943 -1.11948615]


In [28]:
# translation 필요
p1o_+mat_vec(R2,(mat_vec(R1,p5)))

array([0.62397155, 1.21602943, 1.22051385])